apiVersion: v1
kind: Secret
metadata:
  name: controlplane-cert
  namespace: "{{ .Namespace }}"
type: Opaque
data:
  kube-serviceaccount.key: {{ .ServiceAccountKey | base64 }}
  client-ca.crt: {{ .ClientCA | base64 }}
  client-ca.key: {{ .ClientCAKey | base64 }}
  serving-kube-apiserver.crt: {{ .ServingCert | base64 }}
  serving-kube-apiserver.key: {{ .ServingCertKey | base64 }}
