apiVersion: v1
kind: Service
metadata:
  name: multicluster-controlplane
  namespace: "{{ .Namespace }}"
  labels:
    component: multicluster-controlplane
spec:
  type: {{ .ServiceType }}
  selector:
    app: multicluster-controlplane
  ports:
    - name: app
      port: 443
      protocol: TCP
      targetPort: 9443
